=== mrinalCodeStore/webTechRepo/XML/stu_dtls.dtd
<?xml version="1.0" ?>

	<!ELEMENT student_details (class)>
	<!ELEMENT class (roll)*>
	<!ELEMENT roll (name,age,marks)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT age (#PCDATA)>
	<!ELEMENT marks (#PCDATA)>
	<!ATTLIST class val CDATA "12" >
	<!ATTLIST roll roll_num CDATA "" >

=== mrinalCodeStore/webTechRepo/XML/xml1_with_dtd_external.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE student_details SYSTEM "stu_dtls.dtd" >

<student_details>
	<class val="12">
		
			<roll roll_num="1">
				<name>John</name>
				<age>18</age>
				<marks>95</marks>	
			</roll>

			<roll roll_num="">
				<name>John</name>
				<age>18</age>
				<marks>95</marks>	
			</roll>

		
	</class>

</student_details>
